### ISSUE TITLE
Flit register ?

### ISSUE THREAD

**Issue by Carreau** [Carreau/SPQR#1]
@takluyver is there a way to flit register ?

And have fun with a lightning talk on roman numeral, cf readme.

**Comment by takluyver** [comment]
When you `--upload`, if the name isn't already registered, it will try to register it for you. There's no separate command to explicitly register without uploading.

Awesome! I will try to get a lightning talk, and let you know how it goes. I'm disappointed that you appear to have used ascii capital letters as identifiers instead of the unicode roman numeral characters `Ⅰ`, `Ⅴ`, etc. Unicode also has roman numerals going up to 100k (`ↈ`):
http://en.wikipedia.org/wiki/Numerals_in_Unicode#Roman_numerals_in_Unicode

**Comment by takluyver** [comment]
To say nothing of Roman Fractions ;-)

http://en.wikipedia.org/wiki/Roman_numerals#Fractions

**Comment by Carreau** [comment]
> Awesome! I will try to get a lightning talk, and let you know how it goes. I'm disappointed that you appear to have used ascii capital letters as identifiers instead of the unicode roman numeral characters Ⅰ, Ⅴ, etc

Did that in 15min, will make unicode identifiers too :-)

100k appear to me  as square-when-the-font-does-not-have-the-unicode-char

**Comment by takluyver** [comment]
Sounds like Macs need better unicode fonts. It shows up fine for me. I can even use it in the terminal:

![screenshot from 2015-04-10 00 11 28](https://cloud.githubusercontent.com/assets/327925/7081796/337d5fe6-df16-11e4-9f5a-397ecdae4878.png)

**Comment by Carreau** [comment]
@takluyver you can now import 1-12,50 (`from roman_count.literals import *`) and have some fun. 

Just uploaded the new version using flit. 

Have fun at Pycon.

**Comment by takluyver** [comment]
Awesome, thanks. Haven't tried to get a lightning talk today because it appears they clash with PyCon dinners, to which I'm going, but I will sign up for one tomorrow.

**Comment by Carreau** [comment]
Sure no problem. 
It was enjoyable to use flit, and you are not obliged to make a lightning talk. 
Hope you are having fun.

**Comment by takluyver** [comment]
I decided to make my lightning talk about flit, and save this for SciPy, where I think it will be more fun anyway.

And my lightning talk only made the reserve bench, anyway, so I probably won't get to give it. Fingers crossed, though. I have slides ready.

**Comment by Carreau** [comment]
Renamed to SPQR, logo and some link to flit.

**Comment by takluyver** [comment]
Excellent :-)
